"""Entry point: AR(Qwen3) -> dLLM(Dream) on-policy distillation training.

Student: Dream-7B, a diffusion LM (loaded with AutoModel + trust_remote_code).
Teacher: Qwen3, a frozen autoregressive LM (loaded with AutoModelForCausalLM).

See opsd_ar2dllm_trainer.OPSDAR2DLLMTrainer for the distillation pipeline.
"""

import os
from dataclasses import dataclass, field
from pathlib import Path

import torch
import wandb

from datasets import load_dataset
from transformers import AutoModel, AutoModelForCausalLM, AutoTokenizer

from trl import (
    ModelConfig,
    ScriptArguments,
    TrlParser,
    get_kbit_device_map,
    get_peft_config,
    get_quantization_config,
)
from trl.experimental.gold import GOLDConfig

from data_collator_ar2dllm import AR2DLLMDataCollator
from opsd_ar2dllm_trainer import OPSDAR2DLLMTrainer


os.environ.setdefault("TRACKIO_SPACE_ID", "trl-trackio")


# === Canonical OPSD training data =============================================
# Each row carries `problem` (what the student sees) and `solution` (privileged
# step-by-step reasoning the teacher sees in its reasoning prompt).
BASELINE_DATASET_ID = "siyanzhao/Openthoughts_math_30k_opsd"
BASELINE_PROBLEM_FIELD = "problem"
BASELINE_SOLUTION_FIELD = "solution"


@dataclass
class CustomScriptArguments(ScriptArguments):
    """Extra args for AR->dLLM OPSD training.

    `--model_name_or_path` (from ModelConfig) is the *student* (Dream).
    The *teacher* (Qwen3) is configured by the `--teacher_*` flags below.
    """

    # --- AR teacher (Qwen3) ---------------------------------------------------
    teacher_model_name_or_path: str = field(
        default="Qwen/Qwen3-8B",
        metadata={"help": "HF id / path of the frozen autoregressive teacher."},
    )
    teacher_model_revision: str = field(
        default=None, metadata={"help": "Revision for the teacher model."}
    )
    teacher_attn_implementation: str = field(
        default="sdpa",
        metadata={"help": "attn impl for the teacher ('sdpa' or 'flash_attention_2')."},
    )
    max_teacher_prompt_length: int = field(
        default=3072,
        metadata={"help": "Max tokens of the chat-templated teacher reasoning prompt "
                          "(holds problem + full reference solution)."},
    )
    max_reasoning_length: int = field(
        default=2048,
        metadata={"help": "Max new tokens the teacher generates for its reasoning."},
    )
    teacher_gen_temperature: float = field(
        default=0.7, metadata={"help": "Sampling temperature for teacher reasoning (<=0 = greedy)."}
    )
    teacher_gen_top_p: float = field(
        default=0.95, metadata={"help": "Top-p for teacher reasoning generation."}
    )
    teacher_gen_top_k: int = field(
        default=20, metadata={"help": "Top-k for teacher reasoning generation (0 = disabled)."}
    )
    reason_first: bool = field(
        default=True,
        metadata={"help": "Run the teacher reasoning phase before teacher forcing."},
    )
    distill_vocab_size: int = field(
        default=0,
        metadata={"help": "Clamp the JSD to this many vocab columns. 0 = min(student, teacher)."},
    )

    # --- Student rollout / loss ----------------------------------------------
    mask_token_id: int = field(
        default=-1, metadata={"help": "Mask token id; -1 = use student tokenizer.mask_token_id."}
    )
    sampling_eps: float = field(
        default=1e-3, metadata={"help": "Lower bound on the antithetic per-example mask rate."}
    )
    max_prompt_length: int = field(
        default=1024, metadata={"help": "Max tokens of the chat-templated student prompt."}
    )
    max_answer_length: int = field(
        default=1024, metadata={"help": "Kept for parity with the collator API (unused here)."}
    )
    top_k_loss: int = field(
        default=0, metadata={"help": "Restrict JSD to top-k teacher tokens. 0 = full vocabulary."}
    )
    jsd_token_clip: float = field(
        default=0.0, metadata={"help": "Per-element JSD clip. 0 = disabled."}
    )
    gen_max_new_tokens: int = field(
        default=256, metadata={"help": "Completion tokens generated by the student per example."}
    )
    gen_steps: int = field(
        default=256, metadata={"help": "Diffusion denoising steps (MUST equal gen_max_new_tokens)."}
    )
    gen_temperature: float = field(
        default=0.2, metadata={"help": "Sampling temperature for diffusion_generate."}
    )
    gen_top_p: float = field(default=0.95, metadata={"help": "Top-p for diffusion_generate."})
    gen_alg: str = field(default="entropy", metadata={"help": "Dream sampler algorithm."})
    gen_alg_temp: float = field(
        default=0.0, metadata={"help": "Temperature for the Dream sampler scoring fn."}
    )
    run_config: str = field(
        default=None, metadata={"help": "Suffix for output_dir and W&B run name."}
    )


def _resolve_dtype(model_args):
    dtype_attr = getattr(model_args, "torch_dtype", None) or getattr(model_args, "dtype", None)
    if dtype_attr is None:
        return torch.bfloat16
    if isinstance(dtype_attr, str):
        return {
            "bfloat16": torch.bfloat16,
            "bf16": torch.bfloat16,
            "float16": torch.float16,
            "fp16": torch.float16,
            "float32": torch.float32,
            "fp32": torch.float32,
        }.get(dtype_attr.lower(), torch.bfloat16)
    return dtype_attr


if __name__ == "__main__":
    parser = TrlParser((CustomScriptArguments, GOLDConfig, ModelConfig))
    script_args, training_args, model_args = parser.parse_args_and_config()

    # Dream is a diffusion LM, not an AR causal LM. task_type=None selects
    # PEFT's generic PeftModel wrapper so `diffusion_generate` still works.
    model_args.lora_task_type = None

    # === Run / output naming ==================================================
    lr_str = f"{training_args.learning_rate:.0e}".replace("e-0", "e-")
    num_processes = int(os.environ.get("WORLD_SIZE", 1))
    effective_bs = (
        training_args.per_device_train_batch_size
        * training_args.gradient_accumulation_steps
        * num_processes
    )

    if script_args.run_config:
        run_name = f"{script_args.run_config}_lr{lr_str}_bs{effective_bs}"
        if not training_args.output_dir.endswith(script_args.run_config):
            training_args.output_dir = str(Path(training_args.output_dir) / script_args.run_config)
    else:
        student_name = model_args.model_name_or_path.split("/")[-1]
        teacher_name = script_args.teacher_model_name_or_path.split("/")[-1]
        run_name = f"opsd_ar2dllm_{teacher_name}_to_{student_name}_lr{lr_str}_bs{effective_bs}"

    print(f"\n{'='*80}\nRUN CONFIGURATION\n{'='*80}")
    print(f"Student (diffusion): {model_args.model_name_or_path}")
    print(f"Teacher (AR)       : {script_args.teacher_model_name_or_path}")
    print(f"WandB run          : {run_name}")
    print(f"Output dir         : {training_args.output_dir}")
    print(f"{'='*80}\n")

    if os.environ.get("LOCAL_RANK", "0") == "0":
        wandb.init(
            entity=getattr(training_args, "wandb_entity", None),
            project=getattr(training_args, "wandb_project", None),
            name=run_name,
            config={
                "student_model": model_args.model_name_or_path,
                "teacher_model": script_args.teacher_model_name_or_path,
                "learning_rate": training_args.learning_rate,
                "per_device_train_batch_size": training_args.per_device_train_batch_size,
                "gradient_accumulation_steps": training_args.gradient_accumulation_steps,
                "effective_batch_size": effective_bs,
                "num_train_epochs": training_args.num_train_epochs,
                "beta": training_args.beta,
                "temperature": training_args.temperature,
                "max_prompt_length": script_args.max_prompt_length,
                "max_teacher_prompt_length": script_args.max_teacher_prompt_length,
                "max_reasoning_length": script_args.max_reasoning_length,
                "reason_first": script_args.reason_first,
                "use_peft": model_args.use_peft,
                "lora_r": model_args.lora_r if model_args.use_peft else None,
                "lora_alpha": model_args.lora_alpha if model_args.use_peft else None,
                "sampling_eps": script_args.sampling_eps,
                "top_k_loss": script_args.top_k_loss if script_args.top_k_loss > 0 else None,
                "jsd_token_clip": script_args.jsd_token_clip if script_args.jsd_token_clip > 0 else None,
                "distill_vocab_size": script_args.distill_vocab_size or None,
                "gen_max_new_tokens": script_args.gen_max_new_tokens,
                "gen_steps": script_args.gen_steps,
                "gen_temperature": script_args.gen_temperature,
                "gen_top_p": script_args.gen_top_p,
                "gen_alg": script_args.gen_alg,
                "gen_alg_temp": script_args.gen_alg_temp,
                "teacher_gen_temperature": script_args.teacher_gen_temperature,
                "teacher_gen_top_p": script_args.teacher_gen_top_p,
                "teacher_gen_top_k": script_args.teacher_gen_top_k,
            },
        )

    model_dtype = _resolve_dtype(model_args)

    # === Tokenizers ===========================================================
    # Student (Dream) and teacher (Qwen3) use separate tokenizers. They share
    # the regular Qwen BPE token range, which is what makes the completion ids
    # transferable and the JSD computable over the overlapping vocabulary.
    student_tokenizer = AutoTokenizer.from_pretrained(
        model_args.model_name_or_path,
        revision=model_args.model_revision,
        trust_remote_code=True,
    )
    teacher_tokenizer = AutoTokenizer.from_pretrained(
        script_args.teacher_model_name_or_path,
        revision=script_args.teacher_model_revision,
        trust_remote_code=True,
    )
    for tok in (student_tokenizer, teacher_tokenizer):
        if tok.pad_token is None:
            tok.pad_token = tok.eos_token
    # Left padding: the student prompt feeds Dream's diffusion rollout and the
    # teacher reasoning prompt feeds Qwen3's batched AR generation.
    student_tokenizer.padding_side = "left"
    teacher_tokenizer.padding_side = "left"

    mask_token_id = (
        script_args.mask_token_id
        if script_args.mask_token_id >= 0
        else student_tokenizer.mask_token_id
    )
    if mask_token_id is None:
        raise ValueError("Student tokenizer has no mask_token_id; pass --mask_token_id explicitly.")
    print(f"[opsd_ar2dllm_train] Using mask_token_id = {mask_token_id}")

    # === Student model (Dream-7B — diffusion LM) ==============================
    print(f"\n{'='*80}\nLoading STUDENT {model_args.model_name_or_path} (dtype={model_dtype})\n{'='*80}\n")
    student_kwargs = dict(
        revision=model_args.model_revision,
        trust_remote_code=True,
        torch_dtype=model_dtype,
        attn_implementation=model_args.attn_implementation or "sdpa",
    )
    quantization_config = get_quantization_config(model_args)
    if quantization_config is not None:
        student_kwargs["device_map"] = get_kbit_device_map()
        student_kwargs["quantization_config"] = quantization_config

    student_model = AutoModel.from_pretrained(model_args.model_name_or_path, **student_kwargs)

    if training_args.gradient_checkpointing:
        # use_reentrant=False is required with PEFT/LoRA: reentrant mode needs
        # an input tensor with requires_grad=True, which integer input_ids do
        # not provide.
        student_model.gradient_checkpointing_enable(
            gradient_checkpointing_kwargs={"use_reentrant": False}
        )

    # === Teacher model (Qwen3 — frozen AR LM) =================================
    print(f"\n{'='*80}\nLoading TEACHER {script_args.teacher_model_name_or_path} (dtype={model_dtype})\n{'='*80}\n")
    teacher_model = AutoModelForCausalLM.from_pretrained(
        script_args.teacher_model_name_or_path,
        revision=script_args.teacher_model_revision,
        torch_dtype=model_dtype,
        attn_implementation=script_args.teacher_attn_implementation,
        trust_remote_code=True,
    )

    # SFTTrainer expects this attr; empty avoids it re-loading the model from str.
    training_args.model_init_kwargs = None

    # === Dataset ==============================================================
    print(f"\n[opsd_ar2dllm_train] Loading dataset: {BASELINE_DATASET_ID}")
    train_dataset = load_dataset(BASELINE_DATASET_ID)["train"]

    # === Data collator ========================================================
    data_collator = AR2DLLMDataCollator(
        student_tokenizer=student_tokenizer,
        teacher_tokenizer=teacher_tokenizer,
        max_prompt_length=script_args.max_prompt_length,
        max_teacher_prompt_length=script_args.max_teacher_prompt_length,
        problem_field=BASELINE_PROBLEM_FIELD,
        solution_field=BASELINE_SOLUTION_FIELD,
        reason_first=script_args.reason_first,
    )

    # === Trainer ==============================================================
    trainer = OPSDAR2DLLMTrainer(
        model=student_model,
        args=training_args,
        data_collator=data_collator,
        train_dataset=train_dataset,
        eval_dataset=None,
        processing_class=student_tokenizer,
        teacher_model=teacher_model,
        teacher_processing_class=teacher_tokenizer,
        peft_config=get_peft_config(model_args),
        mask_token_id=mask_token_id,
        sampling_eps=script_args.sampling_eps,
        max_prompt_length=script_args.max_prompt_length,
        max_answer_length=script_args.max_answer_length,
        top_k_loss=script_args.top_k_loss if script_args.top_k_loss > 0 else None,
        jsd_token_clip=script_args.jsd_token_clip if script_args.jsd_token_clip > 0 else None,
        distill_vocab_size=script_args.distill_vocab_size or None,
        reason_first=script_args.reason_first,
        max_reasoning_length=script_args.max_reasoning_length,
        teacher_gen_temperature=script_args.teacher_gen_temperature,
        teacher_gen_top_p=script_args.teacher_gen_top_p,
        teacher_gen_top_k=script_args.teacher_gen_top_k,
        gen_max_new_tokens=script_args.gen_max_new_tokens,
        gen_steps=script_args.gen_steps,
        gen_temperature=script_args.gen_temperature,
        gen_top_p=script_args.gen_top_p,
        gen_alg=script_args.gen_alg,
        gen_alg_temp=script_args.gen_alg_temp,
    )

    trainer.train()
    trainer.save_model(training_args.output_dir)
